# This workflow will do a clean install of dependencies, optionally build, and run tests
# across different versions of node.
name: Build
on:
  push:
    branches:
      - "**" # make it run on any branch
      - "!main" # but exclude the 'main'
  pull_request:
    branches:
      - "**"
      - "!main"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - "18.x"
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: pnpm install --frozen-lockfile
      - run: pnpm run build
      # - run: npm test
